name: Deployment pipeline
on:
  push:
    branches:
      - develop
      - release/**
      - feature/**
      - bugfix/**

# Stop concurrent runs on the same branch
concurrency: ${{ github.head_ref ||  github.ref }}

jobs:
  tf-scan:
    name: Scan Terraform
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: make tf.lint

  verify-version:
    name: Verify version does not exist
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          VERSION=$(cat VERSION)
          if [ $(git tag -l "$VERSION") ]; then
              echo "Version already exist"
              exit 1;
          fi

  create-tag:
    name: Create Git Tag
    runs-on: ubuntu-22.04
    needs: [verify-version, tf-scan]
    if: startsWith(github.ref_name, 'develop')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          VERSION=$(cat VERSION)
          git tag $VERSION
          git push origin $VERSION
  
  
      