name: Deployment pipeline
on:
  push:
    branches:
      - develop
      - release/**
      - feature/**
      - bugfix/**

# Stop concurrent runs on the same branch
concurrency: ${{ github.head_ref ||  github.ref }}


# Workflow Permissions
permissions:
  contents: read
  pull-requests: write
  packages: read

jobs:
  tf-scan:
    name: Scan Terraform
    runs-on: ubuntu-22.04
    container: ghcr.io/slypreceipts/ci-python:3.9
    steps:
      - uses: actions/checkout@v3
      - run: make tf.lint
      